# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'DSC_Troubleshooting_Tool.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(1339, 686)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(232, 232, 232))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(221, 225, 214))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.NoRole, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(232, 232, 232))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(221, 225, 214))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.NoRole, brush)
        brush = QtGui.QBrush(QtGui.QColor(232, 232, 232))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(232, 232, 232))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(221, 225, 214))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.NoRole, brush)
        MainWindow.setPalette(palette)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/dsc/dsc.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setWindowOpacity(1.0)
        MainWindow.setAutoFillBackground(False)
        MainWindow.setAnimated(True)
        MainWindow.setDockOptions(QtWidgets.QMainWindow.AllowTabbedDocks|QtWidgets.QMainWindow.AnimatedDocks)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(20, 60, 1301, 581))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(232, 232, 232))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(232, 232, 232))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(232, 232, 232))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(232, 232, 232))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.tabWidget.setPalette(palette)
        self.tabWidget.setAutoFillBackground(True)
        self.tabWidget.setStyleSheet("")
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tabWidget.setElideMode(QtCore.Qt.ElideNone)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.pushButton_input_alarms = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_input_alarms.setGeometry(QtCore.QRect(310, 10, 611, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_input_alarms.setFont(font)
        self.pushButton_input_alarms.setAutoFillBackground(False)
        self.pushButton_input_alarms.setDefault(False)
        self.pushButton_input_alarms.setObjectName("pushButton_input_alarms")
        self.textEdit_resultlog_troubleshooting = QtWidgets.QTextEdit(self.tab_2)
        self.textEdit_resultlog_troubleshooting.setGeometry(QtCore.QRect(740, 190, 541, 301))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(232, 232, 232))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.textEdit_resultlog_troubleshooting.setPalette(palette)
        self.textEdit_resultlog_troubleshooting.setObjectName("textEdit_resultlog_troubleshooting")
        self.label_22 = QtWidgets.QLabel(self.tab_2)
        self.label_22.setGeometry(QtCore.QRect(20, 190, 311, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        font.setItalic(True)
        font.setKerning(True)
        self.label_22.setFont(font)
        self.label_22.setAutoFillBackground(False)
        self.label_22.setTextFormat(QtCore.Qt.AutoText)
        self.label_22.setObjectName("label_22")
        self.label_23 = QtWidgets.QLabel(self.tab_2)
        self.label_23.setGeometry(QtCore.QRect(630, -40, 71, 16))
        self.label_23.setObjectName("label_23")
        self.line_6 = QtWidgets.QFrame(self.tab_2)
        self.line_6.setGeometry(QtCore.QRect(20, 160, 1261, 20))
        self.line_6.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.line_7 = QtWidgets.QFrame(self.tab_2)
        self.line_7.setGeometry(QtCore.QRect(20, 40, 1261, 20))
        self.line_7.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_7.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_7.setObjectName("line_7")
        self.pushButton_sendemail = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_sendemail.setGeometry(QtCore.QRect(870, 500, 261, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        self.pushButton_sendemail.setFont(font)
        self.pushButton_sendemail.setCheckable(False)
        self.pushButton_sendemail.setAutoDefault(False)
        self.pushButton_sendemail.setDefault(False)
        self.pushButton_sendemail.setFlat(False)
        self.pushButton_sendemail.setObjectName("pushButton_sendemail")
        self.layoutWidget = QtWidgets.QWidget(self.tab_2)
        self.layoutWidget.setGeometry(QtCore.QRect(370, 190, 351, 83))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.pushButton_netstat_2 = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_netstat_2.setFont(font)
        self.pushButton_netstat_2.setObjectName("pushButton_netstat_2")
        self.gridLayout_2.addWidget(self.pushButton_netstat_2, 0, 0, 1, 1)
        self.lineEdit_netstatcmd_2 = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_netstatcmd_2.setText("")
        self.lineEdit_netstatcmd_2.setObjectName("lineEdit_netstatcmd_2")
        self.gridLayout_2.addWidget(self.lineEdit_netstatcmd_2, 0, 1, 1, 1)
        self.pushButton_s2sping_2 = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_s2sping_2.setFont(font)
        self.pushButton_s2sping_2.setObjectName("pushButton_s2sping_2")
        self.gridLayout_2.addWidget(self.pushButton_s2sping_2, 1, 0, 1, 1)
        self.lineEdit_s2spingcmd_2 = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_s2spingcmd_2.setText("")
        self.lineEdit_s2spingcmd_2.setObjectName("lineEdit_s2spingcmd_2")
        self.gridLayout_2.addWidget(self.lineEdit_s2spingcmd_2, 1, 1, 1, 1)
        self.pushButton_s2stracert_2 = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_s2stracert_2.setFont(font)
        self.pushButton_s2stracert_2.setObjectName("pushButton_s2stracert_2")
        self.gridLayout_2.addWidget(self.pushButton_s2stracert_2, 2, 0, 1, 1)
        self.lineEdit_s2stracertcmd_2 = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_s2stracertcmd_2.setText("")
        self.lineEdit_s2stracertcmd_2.setObjectName("lineEdit_s2stracertcmd_2")
        self.gridLayout_2.addWidget(self.lineEdit_s2stracertcmd_2, 2, 1, 1, 1)
        self.layoutWidget1 = QtWidgets.QWidget(self.tab_2)
        self.layoutWidget1.setGeometry(QtCore.QRect(22, 221, 341, 54))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.layoutWidget1)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.pushButton_p2pping_2 = QtWidgets.QPushButton(self.layoutWidget1)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_p2pping_2.setFont(font)
        self.pushButton_p2pping_2.setObjectName("pushButton_p2pping_2")
        self.gridLayout_4.addWidget(self.pushButton_p2pping_2, 0, 0, 1, 1)
        self.lineEdit_p2ppingcmd_2 = QtWidgets.QLineEdit(self.layoutWidget1)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(232, 232, 232))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.lineEdit_p2ppingcmd_2.setPalette(palette)
        self.lineEdit_p2ppingcmd_2.setText("")
        self.lineEdit_p2ppingcmd_2.setObjectName("lineEdit_p2ppingcmd_2")
        self.gridLayout_4.addWidget(self.lineEdit_p2ppingcmd_2, 0, 1, 1, 1)
        self.pushButton_p2ptracert_2 = QtWidgets.QPushButton(self.layoutWidget1)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_p2ptracert_2.setFont(font)
        self.pushButton_p2ptracert_2.setObjectName("pushButton_p2ptracert_2")
        self.gridLayout_4.addWidget(self.pushButton_p2ptracert_2, 1, 0, 1, 1)
        self.lineEdit_p2ptracertcmd_2 = QtWidgets.QLineEdit(self.layoutWidget1)
        self.lineEdit_p2ptracertcmd_2.setText("")
        self.lineEdit_p2ptracertcmd_2.setObjectName("lineEdit_p2ptracertcmd_2")
        self.gridLayout_4.addWidget(self.lineEdit_p2ptracertcmd_2, 1, 1, 1, 1)
        self.comboBox_alarm_list = QtWidgets.QComboBox(self.tab_2)
        self.comboBox_alarm_list.setGeometry(QtCore.QRect(91, 110, 60, 20))
        self.comboBox_alarm_list.setMaximumSize(QtCore.QSize(60, 16777215))
        self.comboBox_alarm_list.setEditable(False)
        self.comboBox_alarm_list.setCurrentText("")
        self.comboBox_alarm_list.setObjectName("comboBox_alarm_list")
        self.label_2 = QtWidgets.QLabel(self.tab_2)
        self.label_2.setGeometry(QtCore.QRect(90, 88, 60, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.line_8 = QtWidgets.QFrame(self.tab_2)
        self.line_8.setGeometry(QtCore.QRect(20, 290, 701, 20))
        self.line_8.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_8.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_8.setObjectName("line_8")
        self.label_27 = QtWidgets.QLabel(self.tab_2)
        self.label_27.setGeometry(QtCore.QRect(60, 320, 241, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        font.setItalic(True)
        font.setKerning(True)
        self.label_27.setFont(font)
        self.label_27.setAutoFillBackground(False)
        self.label_27.setTextFormat(QtCore.Qt.AutoText)
        self.label_27.setObjectName("label_27")
        self.layoutWidget2 = QtWidgets.QWidget(self.tab_2)
        self.layoutWidget2.setGeometry(QtCore.QRect(191, 62, 981, 88))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.layoutWidget2)
        self.gridLayout_6.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.label_14 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_14.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_14.setObjectName("label_14")
        self.gridLayout_6.addWidget(self.label_14, 0, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_4.setObjectName("label_4")
        self.gridLayout_6.addWidget(self.label_4, 0, 1, 1, 1)
        self.gridLayout_5 = QtWidgets.QGridLayout()
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.label_28 = QtWidgets.QLabel(self.layoutWidget2)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Shadow, brush)
        self.label_28.setPalette(palette)
        self.label_28.setAutoFillBackground(True)
        self.label_28.setObjectName("label_28")
        self.gridLayout_5.addWidget(self.label_28, 0, 0, 1, 2)
        self.lineEdit_connected_dsc = QtWidgets.QLineEdit(self.layoutWidget2)
        self.lineEdit_connected_dsc.setMaximumSize(QtCore.QSize(100, 16777215))
        self.lineEdit_connected_dsc.setAutoFillBackground(True)
        self.lineEdit_connected_dsc.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_connected_dsc.setObjectName("lineEdit_connected_dsc")
        self.gridLayout_5.addWidget(self.lineEdit_connected_dsc, 1, 0, 1, 1)
        self.lineEdit_connected_dsc_2 = QtWidgets.QLineEdit(self.layoutWidget2)
        self.lineEdit_connected_dsc_2.setMaximumSize(QtCore.QSize(100, 16777215))
        self.lineEdit_connected_dsc_2.setAutoFillBackground(True)
        self.lineEdit_connected_dsc_2.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_connected_dsc_2.setObjectName("lineEdit_connected_dsc_2")
        self.gridLayout_5.addWidget(self.lineEdit_connected_dsc_2, 1, 1, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_13.setObjectName("label_13")
        self.gridLayout_5.addWidget(self.label_13, 2, 0, 1, 1)
        self.label_21 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_21.setObjectName("label_21")
        self.gridLayout_5.addWidget(self.label_21, 2, 1, 1, 1)
        self.lineEdit_peerpip = QtWidgets.QLineEdit(self.layoutWidget2)
        self.lineEdit_peerpip.setMaximumSize(QtCore.QSize(100, 16777215))
        self.lineEdit_peerpip.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_peerpip.setObjectName("lineEdit_peerpip")
        self.gridLayout_5.addWidget(self.lineEdit_peerpip, 3, 0, 1, 1)
        self.lineEdit_peersip = QtWidgets.QLineEdit(self.layoutWidget2)
        self.lineEdit_peersip.setMaximumSize(QtCore.QSize(100, 16777215))
        self.lineEdit_peersip.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_peersip.setObjectName("lineEdit_peersip")
        self.gridLayout_5.addWidget(self.lineEdit_peersip, 3, 1, 1, 1)
        self.gridLayout_6.addLayout(self.gridLayout_5, 0, 2, 4, 1)
        self.label_3 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_3.setObjectName("label_3")
        self.gridLayout_6.addWidget(self.label_3, 0, 3, 1, 1)
        self.lineEdit_customer = QtWidgets.QLineEdit(self.layoutWidget2)
        self.lineEdit_customer.setMinimumSize(QtCore.QSize(150, 0))
        self.lineEdit_customer.setMaximumSize(QtCore.QSize(150, 16777215))
        self.lineEdit_customer.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_customer.setObjectName("lineEdit_customer")
        self.gridLayout_6.addWidget(self.lineEdit_customer, 1, 0, 1, 1)
        self.lineEdit_peer_name = QtWidgets.QLineEdit(self.layoutWidget2)
        self.lineEdit_peer_name.setMinimumSize(QtCore.QSize(200, 0))
        self.lineEdit_peer_name.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_peer_name.setObjectName("lineEdit_peer_name")
        self.gridLayout_6.addWidget(self.lineEdit_peer_name, 1, 1, 1, 1)
        self.lineEdit_alarm = QtWidgets.QLineEdit(self.layoutWidget2)
        self.lineEdit_alarm.setMaximumSize(QtCore.QSize(50, 16777215))
        self.lineEdit_alarm.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_alarm.setObjectName("lineEdit_alarm")
        self.gridLayout_6.addWidget(self.lineEdit_alarm, 1, 3, 1, 1)
        self.label_24 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_24.setObjectName("label_24")
        self.gridLayout_6.addWidget(self.label_24, 2, 0, 1, 1)
        self.label_17 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_17.setObjectName("label_17")
        self.gridLayout_6.addWidget(self.label_17, 2, 1, 1, 1)
        self.label_25 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_25.setObjectName("label_25")
        self.gridLayout_6.addWidget(self.label_25, 2, 3, 1, 1)
        self.lineEdit_time = QtWidgets.QLineEdit(self.layoutWidget2)
        self.lineEdit_time.setMinimumSize(QtCore.QSize(150, 0))
        self.lineEdit_time.setMaximumSize(QtCore.QSize(150, 16777215))
        self.lineEdit_time.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_time.setObjectName("lineEdit_time")
        self.gridLayout_6.addWidget(self.lineEdit_time, 3, 0, 1, 1)
        self.lineEdit_alarm_description = QtWidgets.QLineEdit(self.layoutWidget2)
        self.lineEdit_alarm_description.setMinimumSize(QtCore.QSize(270, 0))
        self.lineEdit_alarm_description.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_alarm_description.setObjectName("lineEdit_alarm_description")
        self.gridLayout_6.addWidget(self.lineEdit_alarm_description, 3, 1, 1, 1)
        self.lineEdit_pingable_2 = QtWidgets.QLineEdit(self.layoutWidget2)
        self.lineEdit_pingable_2.setMaximumSize(QtCore.QSize(50, 16777215))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        self.lineEdit_pingable_2.setPalette(palette)
        self.lineEdit_pingable_2.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_pingable_2.setObjectName("lineEdit_pingable_2")
        self.gridLayout_6.addWidget(self.lineEdit_pingable_2, 3, 3, 1, 1)
        self.label_31 = QtWidgets.QLabel(self.tab_2)
        self.label_31.setGeometry(QtCore.QRect(800, 540, 431, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_31.setFont(font)
        self.label_31.setObjectName("label_31")
        self.widget = QtWidgets.QWidget(self.tab_2)
        self.widget.setGeometry(QtCore.QRect(15, 360, 701, 54))
        self.widget.setObjectName("widget")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.widget)
        self.gridLayout_8.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.pushButton_show_route = QtWidgets.QPushButton(self.widget)
        self.pushButton_show_route.setObjectName("pushButton_show_route")
        self.gridLayout_8.addWidget(self.pushButton_show_route, 0, 0, 1, 1)
        self.lineEdit_show_route = QtWidgets.QLineEdit(self.widget)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(232, 232, 232))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.lineEdit_show_route.setPalette(palette)
        self.lineEdit_show_route.setText("")
        self.lineEdit_show_route.setObjectName("lineEdit_show_route")
        self.gridLayout_8.addWidget(self.lineEdit_show_route, 0, 1, 1, 1)
        self.pushButton_show_route_customer = QtWidgets.QPushButton(self.widget)
        self.pushButton_show_route_customer.setObjectName("pushButton_show_route_customer")
        self.gridLayout_8.addWidget(self.pushButton_show_route_customer, 1, 0, 1, 1)
        self.lineEdit_show_route_customer = QtWidgets.QLineEdit(self.widget)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(232, 232, 232))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.lineEdit_show_route_customer.setPalette(palette)
        self.lineEdit_show_route_customer.setText("")
        self.lineEdit_show_route_customer.setObjectName("lineEdit_show_route_customer")
        self.gridLayout_8.addWidget(self.lineEdit_show_route_customer, 1, 1, 1, 1)
        self.tabWidget.addTab(self.tab_2, "")
        self.Tab_1 = QtWidgets.QWidget()
        self.Tab_1.setMouseTracking(False)
        self.Tab_1.setFocusPolicy(QtCore.Qt.TabFocus)
        self.Tab_1.setObjectName("Tab_1")
        self.line = QtWidgets.QFrame(self.Tab_1)
        self.line.setGeometry(QtCore.QRect(1, 805, 520, 16))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.textEdit_7 = QtWidgets.QTextEdit(self.Tab_1)
        self.textEdit_7.setGeometry(QtCore.QRect(1, 888, 256, 192))
        self.textEdit_7.setObjectName("textEdit_7")
        self.label_5 = QtWidgets.QLabel(self.Tab_1)
        self.label_5.setGeometry(QtCore.QRect(320, 260, 64, 16))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.Tab_1)
        self.label_6.setGeometry(QtCore.QRect(170, 260, 49, 16))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.Tab_1)
        self.label_7.setGeometry(QtCore.QRect(890, 20, 71, 16))
        self.label_7.setObjectName("label_7")
        self.textEdit_resultlog = QtWidgets.QTextEdit(self.Tab_1)
        self.textEdit_resultlog.setGeometry(QtCore.QRect(520, 40, 761, 491))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.textEdit_resultlog.setPalette(palette)
        self.textEdit_resultlog.setAutoFillBackground(True)
        self.textEdit_resultlog.setObjectName("textEdit_resultlog")
        self.label_8 = QtWidgets.QLabel(self.Tab_1)
        self.label_8.setGeometry(QtCore.QRect(20, 240, 421, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        font.setItalic(True)
        font.setKerning(True)
        self.label_8.setFont(font)
        self.label_8.setAutoFillBackground(False)
        self.label_8.setTextFormat(QtCore.Qt.AutoText)
        self.label_8.setObjectName("label_8")
        self.lineEdit_netstatcmd = QtWidgets.QLineEdit(self.Tab_1)
        self.lineEdit_netstatcmd.setGeometry(QtCore.QRect(130, 370, 311, 20))
        self.lineEdit_netstatcmd.setText("")
        self.lineEdit_netstatcmd.setObjectName("lineEdit_netstatcmd")
        self.pushButton_netstat = QtWidgets.QPushButton(self.Tab_1)
        self.pushButton_netstat.setGeometry(QtCore.QRect(20, 370, 75, 23))
        self.pushButton_netstat.setObjectName("pushButton_netstat")
        self.line_2 = QtWidgets.QFrame(self.Tab_1)
        self.line_2.setGeometry(QtCore.QRect(20, 350, 421, 16))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.label_15 = QtWidgets.QLabel(self.Tab_1)
        self.label_15.setGeometry(QtCore.QRect(20, 20, 421, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        font.setItalic(True)
        font.setKerning(True)
        self.label_15.setFont(font)
        self.label_15.setAutoFillBackground(False)
        self.label_15.setTextFormat(QtCore.Qt.AutoText)
        self.label_15.setObjectName("label_15")
        self.line_3 = QtWidgets.QFrame(self.Tab_1)
        self.line_3.setGeometry(QtCore.QRect(20, 30, 421, 16))
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.line_4 = QtWidgets.QFrame(self.Tab_1)
        self.line_4.setGeometry(QtCore.QRect(20, 250, 421, 21))
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.label_18 = QtWidgets.QLabel(self.Tab_1)
        self.label_18.setGeometry(QtCore.QRect(20, 340, 421, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        font.setItalic(True)
        font.setKerning(True)
        self.label_18.setFont(font)
        self.label_18.setAutoFillBackground(False)
        self.label_18.setTextFormat(QtCore.Qt.AutoText)
        self.label_18.setObjectName("label_18")
        self.layoutWidget3 = QtWidgets.QWidget(self.Tab_1)
        self.layoutWidget3.setGeometry(QtCore.QRect(30, 129, 71, 101))
        self.layoutWidget3.setObjectName("layoutWidget3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget3)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_9 = QtWidgets.QLabel(self.layoutWidget3)
        self.label_9.setObjectName("label_9")
        self.verticalLayout_2.addWidget(self.label_9)
        self.label_10 = QtWidgets.QLabel(self.layoutWidget3)
        self.label_10.setObjectName("label_10")
        self.verticalLayout_2.addWidget(self.label_10)
        self.label_11 = QtWidgets.QLabel(self.layoutWidget3)
        self.label_11.setObjectName("label_11")
        self.verticalLayout_2.addWidget(self.label_11)
        self.label_12 = QtWidgets.QLabel(self.layoutWidget3)
        self.label_12.setObjectName("label_12")
        self.verticalLayout_2.addWidget(self.label_12)
        self.layoutWidget4 = QtWidgets.QWidget(self.Tab_1)
        self.layoutWidget4.setGeometry(QtCore.QRect(130, 410, 311, 48))
        self.layoutWidget4.setObjectName("layoutWidget4")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.layoutWidget4)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.lineEdit_p2ppingcmd = QtWidgets.QLineEdit(self.layoutWidget4)
        self.lineEdit_p2ppingcmd.setText("")
        self.lineEdit_p2ppingcmd.setObjectName("lineEdit_p2ppingcmd")
        self.verticalLayout_3.addWidget(self.lineEdit_p2ppingcmd)
        self.lineEdit_p2ptracertcmd = QtWidgets.QLineEdit(self.layoutWidget4)
        self.lineEdit_p2ptracertcmd.setText("")
        self.lineEdit_p2ptracertcmd.setObjectName("lineEdit_p2ptracertcmd")
        self.verticalLayout_3.addWidget(self.lineEdit_p2ptracertcmd)
        self.layoutWidget5 = QtWidgets.QWidget(self.Tab_1)
        self.layoutWidget5.setGeometry(QtCore.QRect(130, 480, 311, 51))
        self.layoutWidget5.setObjectName("layoutWidget5")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.layoutWidget5)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.lineEdit_s2spingcmd = QtWidgets.QLineEdit(self.layoutWidget5)
        self.lineEdit_s2spingcmd.setText("")
        self.lineEdit_s2spingcmd.setObjectName("lineEdit_s2spingcmd")
        self.verticalLayout_4.addWidget(self.lineEdit_s2spingcmd)
        self.lineEdit_s2stracertcmd = QtWidgets.QLineEdit(self.layoutWidget5)
        self.lineEdit_s2stracertcmd.setText("")
        self.lineEdit_s2stracertcmd.setObjectName("lineEdit_s2stracertcmd")
        self.verticalLayout_4.addWidget(self.lineEdit_s2stracertcmd)
        self.layoutWidget6 = QtWidgets.QWidget(self.Tab_1)
        self.layoutWidget6.setGeometry(QtCore.QRect(20, 410, 77, 54))
        self.layoutWidget6.setObjectName("layoutWidget6")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.layoutWidget6)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.pushButton_p2pping = QtWidgets.QPushButton(self.layoutWidget6)
        self.pushButton_p2pping.setObjectName("pushButton_p2pping")
        self.verticalLayout_5.addWidget(self.pushButton_p2pping)
        self.pushButton_p2ptracert = QtWidgets.QPushButton(self.layoutWidget6)
        self.pushButton_p2ptracert.setObjectName("pushButton_p2ptracert")
        self.verticalLayout_5.addWidget(self.pushButton_p2ptracert)
        self.layoutWidget7 = QtWidgets.QWidget(self.Tab_1)
        self.layoutWidget7.setGeometry(QtCore.QRect(20, 480, 77, 54))
        self.layoutWidget7.setObjectName("layoutWidget7")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.layoutWidget7)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.pushButton_s2sping = QtWidgets.QPushButton(self.layoutWidget7)
        self.pushButton_s2sping.setObjectName("pushButton_s2sping")
        self.verticalLayout_6.addWidget(self.pushButton_s2sping)
        self.pushButton_s2stracert = QtWidgets.QPushButton(self.layoutWidget7)
        self.pushButton_s2stracert.setObjectName("pushButton_s2stracert")
        self.verticalLayout_6.addWidget(self.pushButton_s2stracert)
        self.layoutWidget8 = QtWidgets.QWidget(self.Tab_1)
        self.layoutWidget8.setGeometry(QtCore.QRect(130, 280, 311, 48))
        self.layoutWidget8.setObjectName("layoutWidget8")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget8)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.lineEdit_dscpip = QtWidgets.QLineEdit(self.layoutWidget8)
        self.lineEdit_dscpip.setText("")
        self.lineEdit_dscpip.setObjectName("lineEdit_dscpip")
        self.gridLayout.addWidget(self.lineEdit_dscpip, 0, 0, 1, 1)
        self.lineEdit_dscsip = QtWidgets.QLineEdit(self.layoutWidget8)
        self.lineEdit_dscsip.setText("")
        self.lineEdit_dscsip.setObjectName("lineEdit_dscsip")
        self.gridLayout.addWidget(self.lineEdit_dscsip, 0, 1, 1, 1)
        self.lineEdit_customerselectedpip = QtWidgets.QLineEdit(self.layoutWidget8)
        self.lineEdit_customerselectedpip.setText("")
        self.lineEdit_customerselectedpip.setObjectName("lineEdit_customerselectedpip")
        self.gridLayout.addWidget(self.lineEdit_customerselectedpip, 1, 0, 1, 1)
        self.lineEdit_customerselectedsip = QtWidgets.QLineEdit(self.layoutWidget8)
        self.lineEdit_customerselectedsip.setText("")
        self.lineEdit_customerselectedsip.setObjectName("lineEdit_customerselectedsip")
        self.gridLayout.addWidget(self.lineEdit_customerselectedsip, 1, 1, 1, 1)
        self.label_20 = QtWidgets.QLabel(self.Tab_1)
        self.label_20.setGeometry(QtCore.QRect(320, 110, 64, 16))
        self.label_20.setObjectName("label_20")
        self.label_19 = QtWidgets.QLabel(self.Tab_1)
        self.label_19.setGeometry(QtCore.QRect(170, 110, 49, 16))
        self.label_19.setObjectName("label_19")
        self.layoutWidget9 = QtWidgets.QWidget(self.Tab_1)
        self.layoutWidget9.setGeometry(QtCore.QRect(131, 130, 311, 100))
        self.layoutWidget9.setObjectName("layoutWidget9")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.layoutWidget9)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.lineEdit_customer1pip = QtWidgets.QLineEdit(self.layoutWidget9)
        self.lineEdit_customer1pip.setText("")
        self.lineEdit_customer1pip.setObjectName("lineEdit_customer1pip")
        self.gridLayout_3.addWidget(self.lineEdit_customer1pip, 0, 0, 1, 1)
        self.lineEdit_customer1sip = QtWidgets.QLineEdit(self.layoutWidget9)
        self.lineEdit_customer1sip.setText("")
        self.lineEdit_customer1sip.setObjectName("lineEdit_customer1sip")
        self.gridLayout_3.addWidget(self.lineEdit_customer1sip, 0, 1, 1, 1)
        self.lineEdit_customer2pip = QtWidgets.QLineEdit(self.layoutWidget9)
        self.lineEdit_customer2pip.setText("")
        self.lineEdit_customer2pip.setObjectName("lineEdit_customer2pip")
        self.gridLayout_3.addWidget(self.lineEdit_customer2pip, 1, 0, 1, 1)
        self.lineEdit_customer2sip = QtWidgets.QLineEdit(self.layoutWidget9)
        self.lineEdit_customer2sip.setText("")
        self.lineEdit_customer2sip.setObjectName("lineEdit_customer2sip")
        self.gridLayout_3.addWidget(self.lineEdit_customer2sip, 1, 1, 1, 1)
        self.lineEdit_customer3pip = QtWidgets.QLineEdit(self.layoutWidget9)
        self.lineEdit_customer3pip.setText("")
        self.lineEdit_customer3pip.setObjectName("lineEdit_customer3pip")
        self.gridLayout_3.addWidget(self.lineEdit_customer3pip, 2, 0, 1, 1)
        self.lineEdit_customer3sip = QtWidgets.QLineEdit(self.layoutWidget9)
        self.lineEdit_customer3sip.setText("")
        self.lineEdit_customer3sip.setObjectName("lineEdit_customer3sip")
        self.gridLayout_3.addWidget(self.lineEdit_customer3sip, 2, 1, 1, 1)
        self.lineEdit_customer4pip = QtWidgets.QLineEdit(self.layoutWidget9)
        self.lineEdit_customer4pip.setText("")
        self.lineEdit_customer4pip.setObjectName("lineEdit_customer4pip")
        self.gridLayout_3.addWidget(self.lineEdit_customer4pip, 3, 0, 1, 1)
        self.lineEdit_customer4sip = QtWidgets.QLineEdit(self.layoutWidget9)
        self.lineEdit_customer4sip.setText("")
        self.lineEdit_customer4sip.setObjectName("lineEdit_customer4sip")
        self.gridLayout_3.addWidget(self.lineEdit_customer4sip, 3, 1, 1, 1)
        self.layoutWidget10 = QtWidgets.QWidget(self.Tab_1)
        self.layoutWidget10.setGeometry(QtCore.QRect(20, 280, 81, 48))
        self.layoutWidget10.setObjectName("layoutWidget10")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.layoutWidget10)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.comboBox_DSC = QtWidgets.QComboBox(self.layoutWidget10)
        self.comboBox_DSC.setObjectName("comboBox_DSC")
        self.verticalLayout_7.addWidget(self.comboBox_DSC)
        self.comboBox_customer = QtWidgets.QComboBox(self.layoutWidget10)
        self.comboBox_customer.setObjectName("comboBox_customer")
        self.verticalLayout_7.addWidget(self.comboBox_customer)
        self.layoutWidget11 = QtWidgets.QWidget(self.Tab_1)
        self.layoutWidget11.setGeometry(QtCore.QRect(30, 53, 92, 51))
        self.layoutWidget11.setObjectName("layoutWidget11")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.layoutWidget11)
        self.verticalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.label_29 = QtWidgets.QLabel(self.layoutWidget11)
        self.label_29.setObjectName("label_29")
        self.verticalLayout_9.addWidget(self.label_29)
        self.label_26 = QtWidgets.QLabel(self.layoutWidget11)
        self.label_26.setObjectName("label_26")
        self.verticalLayout_9.addWidget(self.label_26)
        self.layoutWidget12 = QtWidgets.QWidget(self.Tab_1)
        self.layoutWidget12.setGeometry(QtCore.QRect(132, 53, 311, 48))
        self.layoutWidget12.setObjectName("layoutWidget12")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.layoutWidget12)
        self.gridLayout_7.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.comboBox_customer_name = QtWidgets.QComboBox(self.layoutWidget12)
        self.comboBox_customer_name.setEditable(True)
        self.comboBox_customer_name.setObjectName("comboBox_customer_name")
        self.gridLayout_7.addWidget(self.comboBox_customer_name, 0, 0, 1, 1)
        self.label_30 = QtWidgets.QLabel(self.layoutWidget12)
        self.label_30.setAutoFillBackground(False)
        self.label_30.setStyleSheet("background-color: rgb(255, 255, 127);")
        self.label_30.setObjectName("label_30")
        self.gridLayout_7.addWidget(self.label_30, 0, 1, 1, 1)
        self.comboBox_customer_peername = QtWidgets.QComboBox(self.layoutWidget12)
        self.comboBox_customer_peername.setEditable(True)
        self.comboBox_customer_peername.setObjectName("comboBox_customer_peername")
        self.gridLayout_7.addWidget(self.comboBox_customer_peername, 1, 0, 1, 1)
        self.lineEdit_customerpeer_pingable = QtWidgets.QLineEdit(self.layoutWidget12)
        self.lineEdit_customerpeer_pingable.setMaximumSize(QtCore.QSize(50, 16777215))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        self.lineEdit_customerpeer_pingable.setPalette(palette)
        self.lineEdit_customerpeer_pingable.setText("")
        self.lineEdit_customerpeer_pingable.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_customerpeer_pingable.setObjectName("lineEdit_customerpeer_pingable")
        self.gridLayout_7.addWidget(self.lineEdit_customerpeer_pingable, 1, 1, 1, 1)
        self.tabWidget.addTab(self.Tab_1, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.tabWidget.addTab(self.tab, "")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(20, 0, 261, 61))
        self.groupBox.setAutoFillBackground(True)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.lineEdit_GID = QtWidgets.QLineEdit(self.groupBox)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 85, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 85, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        self.lineEdit_GID.setPalette(palette)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_GID.setFont(font)
        self.lineEdit_GID.setStyleSheet("")
        self.lineEdit_GID.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lineEdit_GID.setReadOnly(True)
        self.lineEdit_GID.setObjectName("lineEdit_GID")
        self.horizontalLayout.addWidget(self.lineEdit_GID)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.label_16 = QtWidgets.QLabel(self.centralwidget)
        self.label_16.setGeometry(QtCore.QRect(470, 650, 351, 16))
        self.label_16.setObjectName("label_16")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.fileOpenAction = QtWidgets.QAction(MainWindow)
        self.fileOpenAction.setObjectName("fileOpenAction")

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "DSC Troubleshooting Tool"))
        self.pushButton_input_alarms.setText(_translate("MainWindow", "Input Alarms"))
        self.label_22.setText(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Arial\'; font-size:9pt; font-weight:400; font-style:italic;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:11pt; font-weight:600; font-style:normal; color:#000000;\">Peer Status Check</span></p></body></html>"))
        self.label_23.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#000000;\">Result Log</span></p></body></html>"))
        self.pushButton_sendemail.setText(_translate("MainWindow", "Send mail to customer"))
        self.pushButton_netstat_2.setText(_translate("MainWindow", "netstat"))
        self.pushButton_s2sping_2.setText(_translate("MainWindow", "S2S: Ping"))
        self.pushButton_s2stracert_2.setText(_translate("MainWindow", "S2S: TraceRT"))
        self.pushButton_p2pping_2.setText(_translate("MainWindow", "P2P: Ping"))
        self.pushButton_p2ptracert_2.setText(_translate("MainWindow", "P2P: TraceRT"))
        self.label_2.setText(_translate("MainWindow", " Alarm List"))
        self.label_27.setText(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Arial\'; font-size:9pt; font-weight:400; font-style:italic;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:11pt; font-weight:600; font-style:normal; color:#000000;\">BGP/IP Prefix Check</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:11pt; font-weight:600; font-style:normal; color:#55aa00;\"><br /></p></body></html>"))
        self.label_14.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">Customer</p></body></html>"))
        self.label_4.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">Peer/Realm Name</p></body></html>"))
        self.label_28.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">Alarm occurred on <span style=\" color:#000000;\">both</span> below DSC</p></body></html>"))
        self.label_13.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">Peer Primary IP</p></body></html>"))
        self.label_21.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">Peer Secondary IP</p></body></html>"))
        self.label_3.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">Alarm</p></body></html>"))
        self.label_24.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">Time</p></body></html>"))
        self.label_17.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">Alarm Description</p></body></html>"))
        self.label_25.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">Pingable</p></body></html>"))
        self.label_31.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#005500;\">Noted: </span><span style=\" font-weight:400; color:#005500;\">If not IP transport issue, besides send mail, please also call *14444(DSS team) </span></p></body></html>"))
        self.pushButton_show_route.setText(_translate("MainWindow", "Show route: DSC PIP"))
        self.pushButton_show_route_customer.setText(_translate("MainWindow", "Show route: Customer PIP"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Troubleshooting Tool"))
        self.label_5.setText(_translate("MainWindow", "Secondary IP"))
        self.label_6.setText(_translate("MainWindow", "Primary IP"))
        self.label_7.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#000000;\">Result Log</span></p></body></html>"))
        self.label_8.setText(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Arial\'; font-size:9pt; font-weight:400; font-style:italic;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-style:normal; color:#0000ff;\">Step2: Choose DSC and customer.</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-style:normal; color:#0000ff;\"><br /></p></body></html>"))
        self.pushButton_netstat.setText(_translate("MainWindow", "netstat"))
        self.label_15.setText(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Arial\'; font-size:9pt; font-weight:400; font-style:italic;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-style:normal; color:#0000ff;\">Step1: Input </span><span style=\" font-weight:600; font-style:normal; color:#0000ff;\">Customer</span><span style=\" font-style:normal; color:#0000ff;\"> </span><span style=\" font-weight:600; font-style:normal; color:#0000ff;\">Name</span><span style=\" font-style:normal; color:#0000ff;\"> </span><span style=\" font-style:normal; color:#ff0000;\">or</span><span style=\" font-style:normal; color:#0000ff;\"> </span><span style=\" font-weight:600; font-style:normal; color:#0000ff;\">Peer</span><span style=\" font-style:normal; color:#0000ff;\"> </span><span style=\" font-weight:600; font-style:normal; color:#0000ff;\">Hostname</span><span style=\" font-style:normal; color:#0000ff;\"> </span><span style=\" font-style:normal; color:#ff0000;\">or </span><span style=\" font-weight:600; font-style:normal; color:#0000ff;\">IP Address</span><span style=\" font-style:normal; color:#0000ff;\">.</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-style:normal; color:#0000ff;\"><br /></p></body></html>"))
        self.label_18.setText(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Arial\'; font-size:9pt; font-weight:400; font-style:italic;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-style:normal; color:#0000ff;\">Step3: Push related command button.</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-style:normal; color:#0000ff;\"><br /></p></body></html>"))
        self.label_9.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">Customer 1</span></p></body></html>"))
        self.label_10.setText(_translate("MainWindow", "Customer 2"))
        self.label_11.setText(_translate("MainWindow", "Customer 3"))
        self.label_12.setText(_translate("MainWindow", "Customer 4"))
        self.pushButton_p2pping.setText(_translate("MainWindow", "P2P: Ping"))
        self.pushButton_p2ptracert.setText(_translate("MainWindow", "P2P: TraceRT"))
        self.pushButton_s2sping.setText(_translate("MainWindow", "S2S: Ping"))
        self.pushButton_s2stracert.setText(_translate("MainWindow", "S2S: TraceRT"))
        self.label_20.setText(_translate("MainWindow", "Secondary IP"))
        self.label_19.setText(_translate("MainWindow", "Primary IP"))
        self.label_29.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">Customer Name</span></p></body></html>"))
        self.label_26.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">Customer Peer</span></p></body></html>"))
        self.label_30.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">Pingable</span></p></body></html>"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Tab_1), _translate("MainWindow", "Ping Tool"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Reserved"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600; color:#005500;\">User</span></p></body></html>"))
        self.label_16.setText(_translate("MainWindow", "<html><head/><body><p>Product of Syniverse Insight Tailor Team. Version: 1.0, 2018-06-06</p><p><br/></p></body></html>"))
        self.fileOpenAction.setText(_translate("MainWindow", "打开"))
        self.fileOpenAction.setToolTip(_translate("MainWindow", "打开"))
        self.fileOpenAction.setShortcut(_translate("MainWindow", "Alt+S"))

import donkey_rc
